<?php

/**
 * @file
 * Adds support for an encrypted USB card reader to Commerce iATS.
 */

define('COMMERCE_IATS_CARD_READER_DELIMITER', '|@|');

/**
 * Implements hook_commerce_payment_method_info_alter().
 *
 * Overrides payment methods for use with Card on File.
 */
function commerce_iats_usb_reader_commerce_payment_method_info_alter(&$payment_methods) {
  $payment_methods['iats_credit_card']['base'] = 'commerce_iats_usb_reader_credit_card';
  $payment_methods['iats_credit_card']['file'] = 'modules/commerce_iats_usb_reader/includes/commerce_iats_usb_reader.credit_card.inc';

  $payment_methods['iats_credit_card_customer_code']['base'] = 'commerce_iats_usb_reader_credit_card_customer_code';
  $payment_methods['iats_credit_card_customer_code']['file'] = 'modules/commerce_iats_usb_reader/includes/commerce_iats_usb_reader.credit_card_customer_code.inc';
}

/**
 * Returns an array of USB card reader types.
 *
 * @return array
 *   Array of USB card reader IDs mapped to names.
 */
function commerce_iats_usb_reader_types() {
  $types = array(
    '00' => 'IDTech SecureMag USB swiper',
    '02' => 'MagTek Dynamag USB swiper',
  );

  return $types;
}

/**
 * Parses a card type from the obfuscated card number contained in
 * an encrypted string.
 *
 * @param string $encrypted_string
 *   The encrypted string from a USB card reader.
 * @param array $valid_types
 *   An array of valid credit card types.
 *
 * @return Mixed
 *   The credit card type as a string or boolean FALSE.
 */
function commerce_iats_usb_reader_parse_card_type_from_encrypted_string($encrypted_string, $valid_types)
{
  module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.credit_card');

  $matches = NULL;

  // Match pattern:
  // ;4222********2220=
  preg_match("/;\d{4}\*+\d{4}\=/", $encrypted_string, $matches);

  if (empty($matches))
  {
    // Match pattern:
    // ;4222222222222220=
    preg_match("/;\d{16}\=/", $encrypted_string, $matches);
  }

  $card_number = substr(substr($matches[0], 1), 0, -1);

  return commerce_payment_validate_credit_card_type($card_number, $valid_types);
}
