<?php

/**
 * @file
 * Adds support for an encrypted USB card reader to Commerce iATS.
 */

define('COMMERCE_IATS_CARD_READER_DELIMITER', '|@|');

/**
 * Implements hook_commerce_payment_method_info_alter().
 *
 * Overrides payment methods for use with Card on File.
 */
function commerce_iats_usb_reader_commerce_payment_method_info_alter(&$payment_methods) {
  $payment_methods['iats_credit_card']['base'] = 'commerce_iats_usb_reader_credit_card';
  $payment_methods['iats_credit_card']['file'] = 'modules/commerce_iats_usb_reader/includes/commerce_iats_usb_reader.credit_card.inc';
}

/**
 * Returns an array of USB card reader types.
 *
 * @return array
 *   Array of USB card reader IDs mapped to names.
 */
function commerce_iats_usb_reader_types() {
  $types = array(
    '00' => 'IDTech SecureMag USB swiper',
    '02' => 'MagTek Dynamag USB swiper',
  );

  return $types;
}

/**
 * Gets base fields settings form fields for credit card based payment methods
 * using a USB card reader.
 *
 * @param array $settings
 *   Form field default values array.
 *
 * @return array
 *   Base fields for settings form.
 */
function commerce_iats_usb_reader_credit_card_settings_form_base(array $settings = NULL) {
  $form = commerce_iats_settings_form_base($settings);

  $form['usb_reader'] = array(
    '#type' => 'checkbox',
    '#title' => 'Enable encrypted USB card reader',
    '#description' => 'Enable to optionally submit card data using an encrypted USB card reader (admin only.)',
    '#default_value' => isset($settings['usb_reader']) ? $settings['usb_reader'] : FALSE,
    '#weight' => 3,
  );

  $form['usb_reader_type'] = array(
    '#type' => 'select',
    '#title' => t('USB card reader type'),
    '#options' => commerce_iats_usb_reader_types(),
    '#default_value' => isset($settings['usb_reader_type']) ? $settings['usb_reader_type'] : NULL,
    '#weight' => 4,
    '#states' => array(
      'visible' => array(
        ':input[name="parameter[payment_method][settings][payment_method][settings][usb_reader]"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['direct_post']['#weight'] = 4;
  $form['process_key']['#weight'] = 5;

  return $form;
}
