<?php

/**
 * Implements hook_commerce_payment_method_info_alter().
 */
function commerce_iats_cardonfile_commerce_payment_method_info_alter(&$payment_methods) {
  $payment_methods['iats_credit_card']['cardonfile'] = array(
    // TODO: Document and write method.
    'charge callback' => 'commerce_iats_cardonfile_credit_card_charge',
    // Called when card on file is updated.
    // TODO: Write method.
    'update callback' => 'commerce_iats_cardonfile_credit_card_update',
    // Called when card on file is deleted.
    // TODO: Write method.
    'delete callback' => 'commerce_iats_cardonfile_credit_card_delete',
  );

  $payment_methods['iats_credit_card_customer_code'] = array(
    'base' => 'commerce_iats_credit_card_customer_code',
    'title' => t('iATS Webservice: Credit card customer code creation'),
    'short_title' => t('iATS Web Service'),
    'display_title' => t('Credit card customer code'),
    'description' => t('Integrates the iATS CustomerLink webservice for the creation of credit card customer codes.'),
    'file' => 'includes/commerce_iats.credit_card_customer_code.inc',
  );
}